package com.matthew.clashofclansmodule;

public class ConstData {

    public final static String TOKEN = "Bearer " + "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjY2ZjBlMDRjLTI1ZGEtNDFkOC05ZDIzLTFlM2RkNzJiYjEwMiIsImlhdCI6MTY1NjM0MzA4OCwic3ViIjoiZGV2ZWxvcGVyLzVlOTkyMzAzLWVmZGYtYTIxMy0wNzU2LTc2OWUyNTg3ZjQwMSIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjE0Ni43MC44NS4yMSJdLCJ0eXBlIjoiY2xpZW50In1dfQ.4_MgIul63HKAdETMJqy3OcULVnwjU40Z64Kpz7FN_fJIso43X22cV8Cdt5vktYsUl6R8Q11Llpo0qHZA_rjiwg";
    public final static String PLAYER_FINDING_URL = "https://api.clashofclans.com/v1/players/%23";
    public final static String CLAN_FINDING_URL = "https://api.clashofclans.com/v1/clans/%23";


}
