package com.matthew.clashofclansmodule;

public class ConstData {

    public final static String TOKEN = "Bearer " + "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6Ijc2ZWI3NjQwLTRlYzktNGMxNy1iYmI5LTE1NWVhYTgzMDAzZCIsImlhdCI6MTY1NjQxOTc0MSwic3ViIjoiZGV2ZWxvcGVyLzVlOTkyMzAzLWVmZGYtYTIxMy0wNzU2LTc2OWUyNTg3ZjQwMSIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjE0Ni43MC44NS4yNSJdLCJ0eXBlIjoiY2xpZW50In1dfQ.QcHrqAqbNjsCQ5s4Z301wFQBXb6s4YbylTurMdKqmnQ_cbpd2cimUODwO3iMPBKlYRyQIiktMFSPeYW06mp_lA";
    public final static String PLAYER_FINDING_URL = "https://api.clashofclans.com/v1/players/%23";
    public final static String CLAN_FINDING_URL = "https://api.clashofclans.com/v1/clans/%23";


}
